### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by metehanpala** [MZehren/Automix#2]
I get the following error when trying to run your example for determining cue points,

`FileNotFoundError: [Errno 2] No such file or directory: 'cuemix/Automix-master/automix/featureExtraction/automaticDrumsTranscription/../../../vendors/madmomDrumsEnv/bin/python'`

I tried to install it locally while keeping it editable with `pip install -e`; however, the problem still occurs. I tried to create some folders matching the criteria but can't even see the full path or understand what's wrong. What should I do?

**Comment by metehanpala** [comment]
It took me several reinstalls; I forgot to cd the correct path for madmomDrumsEnv, so it was created in `venv/lib/site-packages` but has to be created in `automix/featureExtraction/automaticDrumsTranscription/../`. In the end, this was my mistake, so I leave this here for others to see If they have the same problem as me.

**Comment by MZehren** [comment]
Thank you for your feedback. I am sorry that you spent some time debugging the issue.

We are working on a better system for the automatic drum transcription. Hopefully, the installation will be easier in the future!
