### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'func'

### ISSUE THREAD

**Issue by 980202006** [MZehren/Automix#4]
I'm having issues installing dependencies like this:
![image](https://user-images.githubusercontent.com/24452502/163762102-58e97c6f-4885-433a-883c-403e229fd6a2.png)

**Comment by 980202006** [comment]
![image](https://user-images.githubusercontent.com/24452502/163762817-618177af-f61c-47c5-864a-30359b7d329f.png)

**Comment by MZehren** [comment]
The script DrumTranscriptor requires to be called with some arguments. The error that you see is a wrong interpretation of "too few arguments error" due to a bug in Python3: See https://stackoverflow.com/a/54161510/2067780

**Comment by 980202006** [comment]
Thank you, I ran it successfully, I noticed that there is a generateMix function, how can I save the output result to an audio file？
![image](https://user-images.githubusercontent.com/24452502/164133781-9a98c2eb-b140-4ba6-8ec8-a9fcf3c92fe9.png)

**Comment by MZehren** [comment]
Good to hear that it's working!

"generateMix" is not currently supported. I will add more functions and release the code as I publish my research!
